name: mon_budget
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.1

dependencies:
  cloud_firestore: ^6.10.0
  firebase_auth: ^6.7.0
  firebase_core: ^4.15.0
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.8
  intl: ^0.20.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  rename_app: ^1.6.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google.png
    - assets/apple.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf

config_name:
  name: "Budgeto"


flutter_native_splash:
  color: "#1F3864"
  image: assets/logo.png
  fullscreen: true

  android_12:
    color: "#1F3864"
    image: assets/logo.png
