// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtCZQNWmSksS85xCR_RBnjwWpPerlzec0',
    appId: '1:663318000998:web:c9e2213300f39f53e444a7',
    messagingSenderId: '663318000998',
    projectId: 'dclic-mon-budget',
    authDomain: 'dclic-mon-budget.firebaseapp.com',
    storageBucket: 'dclic-mon-budget.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiOfuVozoR0EQvwG4Mns80Qhg7GUuU9mM',
    appId: '1:663318000998:android:2619f562d25c9dd6e444a7',
    messagingSenderId: '663318000998',
    projectId: 'dclic-mon-budget',
    storageBucket: 'dclic-mon-budget.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxQA8bl5kRC92J1yKl2PL9Q7Ii8QKPhtM',
    appId: '1:663318000998:ios:97e2b93fb09b3d76e444a7',
    messagingSenderId: '663318000998',
    projectId: 'dclic-mon-budget',
    storageBucket: 'dclic-mon-budget.firebasestorage.app',
    iosBundleId: 'com.yamariel.org.monBudget',
  );
}
